import NavBar from '@/components/NavBar';
import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'LegalCenter',
  description: 'Generated by create next app',
};

export default function ServicesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className='relative h-full min-h-screen'>
      <NavBar />
      {children}
    </section>
  );
}
