import './globals.css';
import type { Metadata } from 'next';
import { Inter, IBM_Plex_Sans } from 'next/font/google';
import Providers from './Providers';
import { Toaster } from '@/components/ui/toaster';
import NavBar from '@/components/NavBar';
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ['latin'], variable: '--inter' });
const ibmPlexSans = IBM_Plex_Sans({
  subsets: ['greek'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--ibmPlexSans',
});

export const metadata: Metadata = {
  title: 'LegalCenter',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={` ${inter.variable} debug-screens ${ibmPlexSans.variable}`}
      >
        <Providers>
          <NavBar />

          <NextTopLoader
            showSpinner={false}
            easing="ease-in-out"
            color="#e48634"
          />
          {children}
        </Providers>
        <Toaster />
      </body>
    </html>
  );
}
