import type { Metadata } from 'next';
import Sidebar from '@/components/Sidebar';
import NavBar from '@/components/NavBar';
export const metadata: Metadata = {
  title: 'LegalCenter',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className=" w-full grid grid-cols-12	 ">
      <div className="col-span-2 relative">
        <Sidebar />
      </div>
      <div className="col-span-10 relative">
        <NavBar />
        {children}
      </div>
    </section>
  );
}
