import type { Metadata } from 'next';
import Sidebar from '@/components/Sidebar';
import NavBar from '@/components/NavBar';
import DashBoardNavbar from '@/components/DashBoardNavbar';
export const metadata: Metadata = {
  title: 'LegalCenter',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className='grid min-h-screen	 w-full grid-cols-12'>
      <div className='relative hidden lg:col-span-2 lg:grid'>
        <Sidebar />
      </div>
      <div className='relative col-span-12 max-h-screen overflow-y-auto bg-gray-50 lg:col-span-10'>
        <DashBoardNavbar />
        {children}
      </div>
    </section>
  );
}
