import type { Metadata } from 'next';
import Sidebar from '@/components/Sidebar';
export const metadata: Metadata = {
  title: 'LegalCenter',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="flex min-h-screen">
      <Sidebar />
      {children}
    </section>
  );
}
